### ISSUE TITLE
Using the modals in Rails with turbo

### ISSUE THREAD

**Issue by code-bunny** [merakiui/premium-templates-support#5]
I am trying to trigger the model on my rails project using the premium-dashboard. It seems to trigger on x-show="true :

```
<% if flash[:error] %>
  <div x-show="true" x-transition:enter="transition ease-out duration-300 transform" x-transition:enter-start="translate-x-20 opacity-0" x-transition:enter-end="translate-x-0 opacity-100" x-transition:leave="transition ease-in duration-200 transform" x-transition:leave-start="translate-x-0 opacity-100" x-transition:leave-end="translate-x-20 opacity-0" class="fixed inset-x-0 lg:inset-x-auto bottom-6 lg:right-8 xl:right-10 xl:bottom-8 rtl:lg:left-8 rtl:lg:right-auto rtl:xl:left-10 rtl:xl:right-auto">
    <div class="px-6 lg:w-96 lg:px-0">
      <div class="p-2 bg-red-500 rounded-lg shadow-lg sm:p-3">
        <div class="flex items-center justify-between text-white">
          <div class="flex items-center flex-1 w-0">
            <p class="mx-3 font-medium">
              <%= flash[:error] %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
```

However this kills the ability fade in, close, and it doesn't auto close. I am not familiar with this particular flavour of JavaScript and could do with an example to follow.

**Comment by khatabwedaa** [comment]
Hey @code-bunny, you have to have a changeable variable to change the element's state after the time run or an X button click it to close the modal otherwise it will not work if you define the x-show to just true.

You can check some examples on Meraki UI website modal example [merakiui.com](https://merakiui.com/components/application-ui/modals)
